services:
  - type: web
    name: attendx
    runtime: python

    plan: free

    buildCommand: ./build.sh

    startCommand: gunicorn run:app --worker-class eventlet --workers 1 --bind 0.0.0.0:$PORT --timeout 300

    autoDeploy: true

    envVars:

      - key: PYTHON_VERSION
        value: 3.11.9

      - key: RENDER
        value: "true"

      - key: FLASK_ENV
        value: production

      - key: DATABASE_PATH
        value: /var/data/attendance.db

      - key: MEDIA_ROOT
        value: /var/data/media

disk:
  name: attendx-data
  mountPath: /var/data
  sizeGB: 5